# Generated by Django 5.2.8 on 2025-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sucursales/'),
        ),
    ]
